menu:
- {name: 'publications', url: '/publications'}
- {name: 'cv', url: '/cv'}
- {name: 'talks', url: '/talks'}
- {name: 'outreach', url: '/outreach'}
- {name: 'teaching', url: '/teaching'}
- {name: 'contact', url: '/contact'}

projects:
- {name: 'NoRaRe Database (Editor)', url: 'https://norare.clld.org/'}
- {name: 'CLICS Database (Editor)', url: 'https://clics.clld.org/'}
- {name: 'Concepticon Database (Editor)', url: 'https://concepticon.clld.org/'}
- {name: 'Computer-Assisted Language Comparison (Affiliate)', url: 'https://calclab.org/'}
- {name: 'Focus Alternatives in the Human Mind - Retrieval, Representation and Recall (former Research Associate)', url: 'https://www.projekte.hu-berlin.de/en/fahmrrr/index.html'}
- {name: 'MelaTAMP (former Student Assisant)', url: 'https://www.projekte.hu-berlin.de/en/melatamp/project%20description'}


teaching:
- {name: 'Sprachdiversität und Mehrsprachigkeit', title: 'Seminar for Bachelor’s students', department: 'University of Passau, Germany', url: 'https://annikatjuka.notion.site/Syllabus-f96f7f25227a47eca5f52df44e51ca74?pvs=74'}
- {name: 'Sprachwissenschaftliche Fragestellungen und Methoden', title: 'Introductory Course for Bachelor’s students', department: 'Freie Universität Berlin, Germany', url: 'https://annikatjuka.notion.site/Syllabus-ed5e07e4e1524639b6c06d9b95af2992'}
- {name: 'Same same but different - Semantic relations in language and thought', title: 'Seminar for Bachelor’s students', department: 'Friedrich Schiller University, Department of English Studies, Jena', url: 'https://annikatjuka.notion.site/Syllabus-ce3997d2d32343e89e7e0f7673666928'}
- {name: 'Words and their meanings across languages', title: 'Seminar for Bachelor’s students', department: 'Friedrich Schiller University, Department of English Studies, Jena', url: 'https://annikatjuka.notion.site/Syllabus-35ec90dab75f4770bc6ead65d9a871f2'}
- {name: 'The mental lexicon from a cross-linguistic perspective', title: 'Seminar for Bachelor’s students', department: 'Friedrich Schiller University, Department of English Studies, Jena', url: 'https://annikatjuka.notion.site/Syllabus-812dc77904e849059d4639d484eecd88'}


outreach:
- {name: 'Long Night of Science Leipzig 2025', title: 'Speaker', department: '', image: 'assets/img/outreach/langenacht.png', url: 'https://www.eva.mpg.de/events/20250620-long-night-of-science/'}
- {name: 'Soapbox Science Berlin 2025', title: 'Speaker', department: 'Anatomie der Sprache: Eine Reise von Kopf bis Fuß', image: 'assets/img/outreach/soapbox.jpg', url: 'https://berlinsoapboxscience.wordpress.com/'}
- {name: 'Three Minute Thesis Competition 2024', title: 'Speaker', department: 'One Body, Many Words: Linguistic Diversity as a Window into the Mind', image: 'assets/img/outreach/tjuka2024_3MTC.png', url: 'https://www.uni-jena.de/en/293073/three-minute-thesis-competition-2025'}
- {name: 'Quantum Entanglement - Science and Music Open Air 2023', title: 'Speaker', department: 'Was wäre, wenn du jede Sprache auf der Welt sprechen könntest?', image: 'assets/img/outreach/quantum.jpg', url: 'https://www.instagram.com/quantumentanglementfestival/'}
- {name: 'Spektrum.de - Thinky & Brain', title: 'Blog Post', department: '', image: 'assets/img/outreach/thinky.png', url: 'https://scilogs.spektrum.de/thinky-brain/von-kopf-bis-fuss-wie-sprachen-koerperteile-benennen/'}
- {name: 'Computer-Assisted Language Comparison in Practice', title: 'Blog Posts', department: '', image: 'assets/img/outreach/blog.jpg', url: 'https://calc.hypotheses.org/author/annikatjuka'}
- {name: 'YouTube', title: 'Videos', department: '', image: 'assets/img/outreach/youtube.jpg', url: 'https://www.youtube.com/channel/UCTwJm5tJzG7TX4sma-5qnBw'}

talks:
- {name: 'Keynote', title: 'Emerging Topics in Typology (ETT) Conference 2025', department: 'Leipzig, Germany', image: 'assets/img/talks/tjuka2025_Keynote_ETT.png', url: 'assets/slides/tjuka2025_Keynote_ETT.pdf'}
- {name: '', title: 'Talk Series: Diversity in Linguistics', department: 'Online', image: 'assets/img/talks/tjuka2025_BodyObjectAnimal_LingDivSeries.png', url: 'https://div-ling.org/wp-content/uploads/2025/05/Tjuka2025-BodyObjectAnimal-LingDiv-Talk.pdf'}
- {name: '', title: 'COGSCI 2024', department: 'Rotterdam, Netherlands', image: 'assets/img/talks/tjuka2024_Body_Colexi.png', url: 'assets/slides/tjuka2024_Body_Colexi.pdf'}
- {name: 'Invited Talk', title: 'Graduate Colloquium at Chair of Multilingual Computational Linguistics', department: 'Passau, Germany', image: 'assets/img/talks/tjuka2024_Directional_Tendencies.png', url: 'assets/slides/tjuka2024_Directional_Tendencies.pdf'}
- {name: '', title: 'Friedrich Schiller University', department: 'Jena, Germany', image: 'assets/img/talks/tjuka2024_Defense.png', url: 'assets/slides/tjuka2024_Defense.pdf'}
- {name: '', title: 'Workshop on Cross-Linguistic Data Formats 2023 - Graphs and Text', department: 'Leipzig, Germany', image: 'assets/img/talks/tjuka2023_Networks_CLDF.png', url: 'assets/slides/tjuka2023_Networks_CLDF.pdf'}
- {name: '', title: '16th International Cognitive Linguistics Conference 2023', department: 'Düsseldorf, Germany', image: 'assets/img/talks/tjuka2023-body-object-partialcolexification-ICLC16.png', url: 'assets/slides/tjuka2023-body-object-partialcolexification-ICLC16.pdf'}
- {name: 'Invited Talk', title: 'Current Topics in General Linguistics - Research Colloquium at Heinrich Heine University', department: 'Düsseldorf, Germany', image: 'assets/img/talks/tjuka2023-body-object-colexification-HHU-Colloquium.png', url: 'assets/slides/tjuka2023-body-object-colexification-HHU-Colloquium.pdf'}


social:
- {icon: 'github', link: 'https://github.com/AnnikaTjuka'}
- {icon: 'researchgate', link: 'https://www.researchgate.net/profile/Annika-Tjuka-2?ev=hdr_xprf'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/annika-tjuka/'}


contacts:
- {name: 'Annika Tjuka', department: 'Department of Linguistic and Cultural Evolution', institution: 'Max Planck Institute for Evolutionary Anthropology', institution_address: 'Leipzig, Germany', email: 'annika_tjuka@eva.mpg.de', image: 'assets/img/contact.jpg'}
